DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS item_request CASCADE;
DROP TABLE IF EXISTS item CASCADE;
DROP TABLE IF EXISTS booking CASCADE;
DROP TABLE IF EXISTS comments CASCADE;

CREATE TABLE IF NOT EXISTS users
(
    user_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_name VARCHAR(30) NOT NULL,
    email VARCHAR(30) UNIQUE NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS item_request
(
    request_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id INT,
    request_description VARCHAR(128) NOT NULL,
    creation_time TIMESTAMP NOT NULL,
    CONSTRAINT pk_request PRIMARY KEY (request_id),
    FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS item
(
    item_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    owner_id INT,
    item_name VARCHAR(30) NOT NULL,
    item_description VARCHAR(128),
    is_available BOOLEAN DEFAULT FALSE,
    request_id INT,
    CONSTRAINT pk_item PRIMARY KEY (item_id),
    FOREIGN KEY (owner_id) REFERENCES users (user_id) ON DELETE CASCADE,
    FOREIGN KEY (request_id) REFERENCES item_request (request_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS booking
(
    booking_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_date TIMESTAMP NOT NULL,
    end_date TIMESTAMP NOT NULL,
    item_id INT,
    booker_id INT,
    status VARCHAR(8) NOT NULL DEFAULT 'WAITING',
    CONSTRAINT pk_booking PRIMARY KEY (booking_id),
    FOREIGN KEY (item_id) REFERENCES item (item_id) ON DELETE CASCADE,
    FOREIGN KEY (booker_id) REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS comments
(
    comment_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text VARCHAR(560) NOT NULL,
    item_id INT,
    author_id INT,
    created TIMESTAMP,
    CONSTRAINT pk_comments PRIMARY KEY (comment_id),
    FOREIGN KEY (item_id) REFERENCES item (item_id) ON DELETE CASCADE,
    FOREIGN KEY (author_id) REFERENCES users (user_id) ON DELETE CASCADE
);